# Generated by Django 5.1.4 on 2024-12-24 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management_system_app', '0007_alter_notification_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='location',
        ),
        migrations.RemoveField(
            model_name='task',
            name='organizer',
        ),
    ]
